# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import platform_pb2 as platform__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in platform_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CoordinatorStub(object):
    """Coordinator Service - runs on main server
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterWorker = channel.unary_unary(
                '/platform.Coordinator/RegisterWorker',
                request_serializer=platform__pb2.WorkerInfo.SerializeToString,
                response_deserializer=platform__pb2.RegistrationResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/platform.Coordinator/Heartbeat',
                request_serializer=platform__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=platform__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.SubmitJob = channel.unary_unary(
                '/platform.Coordinator/SubmitJob',
                request_serializer=platform__pb2.JobRequest.SerializeToString,
                response_deserializer=platform__pb2.JobResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/platform.Coordinator/GetStatus',
                request_serializer=platform__pb2.Empty.SerializeToString,
                response_deserializer=platform__pb2.ClusterStatus.FromString,
                _registered_method=True)
        self.StreamJobLogs = channel.unary_stream(
                '/platform.Coordinator/StreamJobLogs',
                request_serializer=platform__pb2.JobLogRequest.SerializeToString,
                response_deserializer=platform__pb2.LogEntry.FromString,
                _registered_method=True)


class CoordinatorServicer(object):
    """Coordinator Service - runs on main server
    """

    def RegisterWorker(self, request, context):
        """Worker calls this to join the cluster
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Worker sends heartbeats every 5 seconds
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitJob(self, request, context):
        """Client submits training job
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Get current cluster status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamJobLogs(self, request, context):
        """Stream job logs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoordinatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=platform__pb2.WorkerInfo.FromString,
                    response_serializer=platform__pb2.RegistrationResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=platform__pb2.HeartbeatRequest.FromString,
                    response_serializer=platform__pb2.HeartbeatResponse.SerializeToString,
            ),
            'SubmitJob': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitJob,
                    request_deserializer=platform__pb2.JobRequest.FromString,
                    response_serializer=platform__pb2.JobResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=platform__pb2.Empty.FromString,
                    response_serializer=platform__pb2.ClusterStatus.SerializeToString,
            ),
            'StreamJobLogs': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamJobLogs,
                    request_deserializer=platform__pb2.JobLogRequest.FromString,
                    response_serializer=platform__pb2.LogEntry.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'platform.Coordinator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('platform.Coordinator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Coordinator(object):
    """Coordinator Service - runs on main server
    """

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/platform.Coordinator/RegisterWorker',
            platform__pb2.WorkerInfo.SerializeToString,
            platform__pb2.RegistrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/platform.Coordinator/Heartbeat',
            platform__pb2.HeartbeatRequest.SerializeToString,
            platform__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/platform.Coordinator/SubmitJob',
            platform__pb2.JobRequest.SerializeToString,
            platform__pb2.JobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/platform.Coordinator/GetStatus',
            platform__pb2.Empty.SerializeToString,
            platform__pb2.ClusterStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamJobLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/platform.Coordinator/StreamJobLogs',
            platform__pb2.JobLogRequest.SerializeToString,
            platform__pb2.LogEntry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WorkerStub(object):
    """Worker Service - runs on each worker
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartTraining = channel.unary_stream(
                '/platform.Worker/StartTraining',
                request_serializer=platform__pb2.TrainingTask.SerializeToString,
                response_deserializer=platform__pb2.TrainingUpdate.FromString,
                _registered_method=True)
        self.StopTraining = channel.unary_unary(
                '/platform.Worker/StopTraining',
                request_serializer=platform__pb2.StopRequest.SerializeToString,
                response_deserializer=platform__pb2.StopResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/platform.Worker/Ping',
                request_serializer=platform__pb2.Empty.SerializeToString,
                response_deserializer=platform__pb2.Pong.FromString,
                _registered_method=True)


class WorkerServicer(object):
    """Worker Service - runs on each worker
    """

    def StartTraining(self, request, context):
        """Coordinator tells worker to start training
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopTraining(self, request, context):
        """Coordinator asks worker to stop
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartTraining': grpc.unary_stream_rpc_method_handler(
                    servicer.StartTraining,
                    request_deserializer=platform__pb2.TrainingTask.FromString,
                    response_serializer=platform__pb2.TrainingUpdate.SerializeToString,
            ),
            'StopTraining': grpc.unary_unary_rpc_method_handler(
                    servicer.StopTraining,
                    request_deserializer=platform__pb2.StopRequest.FromString,
                    response_serializer=platform__pb2.StopResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=platform__pb2.Empty.FromString,
                    response_serializer=platform__pb2.Pong.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'platform.Worker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('platform.Worker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Worker(object):
    """Worker Service - runs on each worker
    """

    @staticmethod
    def StartTraining(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/platform.Worker/StartTraining',
            platform__pb2.TrainingTask.SerializeToString,
            platform__pb2.TrainingUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopTraining(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/platform.Worker/StopTraining',
            platform__pb2.StopRequest.SerializeToString,
            platform__pb2.StopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/platform.Worker/Ping',
            platform__pb2.Empty.SerializeToString,
            platform__pb2.Pong.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
